'use strict';
const Generator = require('yeoman-generator');
const chalk = require('chalk');
const yosay = require('yosay');
const relayOption = {
    mobx: {
      "mobx": "^3.2.2",
      "mobx-react": "^4.2.2",
    },
    redux: {
      "redux": "^3.7.2",
      "react-redux": "^5.0.5"
    }
  }
module.exports = class extends Generator {
  initializing() {
    this.log(chalk.yellow("**********************************************************"));
    // Have Yeoman greet the user.
    let greetWord = 'Welcome to Use ' + chalk.red.bold('generator-berton-react') + ' ' +
      chalk.blue('JerryBerton ');
    this.log(yosay(greetWord));
    this.log(chalk.yellow("**********************************************************"));
  }
  prompting() {
    const prompts = [{
        type: 'input',
        name: 'name',
        message : 'Your project name',
        default: 'berton-test'
      }, {
        type: 'input',
        name: 'author',
        message : 'Your project author',
        default: 'JerryBerton'
      }, {
        type: 'input',
        name: 'repository',
        message : 'Your project git repository url',
        default: ' '
      }, {
        type: 'list',
        name: 'relay',
        message: 'The state of data management framework',
        choices: ['redux', 'mobx']
      }, {
        type: 'confirm',
        name: 'eslint',
        message: 'would you like to enable this option for Eslint ?',
        default: true
      }
    ];
    return this.prompt(prompts).then(props => {
      this.props = props;
    });
  }
  configuring() {
    let defaultSettings = this.fs.readJSON(this.templatePath('default.json'));
    let packageInfo = {
      name: this.props.name,
      private: true,
      version: '0.0.0',
      description: `${this.props.name} - Generated by generator-berton-react`,
      main: 'src/index.js',
      scripts: defaultSettings.scripts,
      repository: this.props.repository,
      keywords: [],
      author: this.props.author,
      devDependencies: defaultSettings.devDependencies,
      dependencies: defaultSettings.dependencies
    }
    packageInfo.dependencies = Object.assign(packageInfo.dependencies, relayOption[this.props.relay])
    if (this.props.eslint) {
      packageInfo.devDependencies =  Object.assign(packageInfo.devDependencies, {
        "eslint": "^4.3.0",
        "eslint-loader": "^1.9.0",
        "eslint-plugin-react": "^7.1.0"
      })
    }
    this.fs.writeJSON(this.destinationPath('package.json'), packageInfo);
  }
  writing() {
    let list = [
      {
        tPath: 'README.md',
        dPath: 'README.md',
        options: { name: this.props.name },
        copy: true
      }, {
          tPath: 'webpack.config.js',
          dPath: 'webpack.config.js',
          copy: true
        }, {
        tPath: '.babelrc',
        dPath: '.babelrc',
        copy: true
      }, {
        tPath: '.eslintrc',
        dPath: '.eslintrc',
        copy: this.props.eslint
      }, {
        tPath: 'src/index.html',
        dPath: 'src/index.html',
        copy: true
      }, {
        tPath: 'src/index.js',
        dPath: 'src/index.js',
        options: { relay: this.props.relay },
        copy: true
      }, {
        tPath: 'src/styles/index.scss',
        dPath: 'src/styles/index.scss',
        copy: true
      }, {
        tPath: 'src/reducer/index.js',
        dPath: 'src/reducer/index.js',
        copy: this.props.relay === 'redux'
      }, {
        tPath: 'src/actions/index.js',
        dPath: 'src/actions/index.js',
        copy: this.props.relay === 'redux'
      }, {
        tPath: `src/store/${this.props.relay}.js`,
        dPath: 'src/store/index.js',
        copy: true
      }, {
        tPath: 'src/components/Layout.js',
        dPath: 'src/components/Layout.js',
        copy: true
      }, {
        tPath: `src/components/${this.props.relay}_home.js`,
        dPath: 'src/components/Home.js',
        copy: true
      }
    ]
    list.filter(c => c.copy).forEach((item) => {
      if (item.options) {
        this.fs.copyTpl(
          this.templatePath(item.tPath),
          this.destinationPath(item.dPath),
          item.options
        )
      } else {
        this.fs.copy(
          this.templatePath(item.tPath),
          this.destinationPath(item.dPath)
        )
      }
    })
  }
  install() {
    this.installDependencies({
      bower: false,
      npm: true,
      yarn: false
    }, () => {
      this.log('node_moudles is end , please run:', 'npm start');
    });
  }
};
